echo 'Running tests'

pushd ./test/TestCoverageWithOpenCover.Tests

if [ ! -d "./../../coverage-results" ]; then
  mkdir ./../../coverage-results
fi

~/.nuget/packages/opencover/4.6.519/tools/OpenCover.Console.exe \
  -target:"/c/Program Files/dotnet/dotnet.exe" \
  -targetargs:"test" \
  -register:user \
  -output:"./../../coverage-results/results.xml" \
  -filter:"+[TestCoverageWithOpenCover.Tests*]* -[TestCoverageWithOpenCover.Tests*]AutoGeneratedProgram*" \
  -hideskipped:Filter \
  -oldStyle

popd

echo 'Building test report'

~/.nuget/packages/reportgenerator/2.5.8/tools/ReportGenerator.exe -reports:"./coverage-results/results.xml" -targetdir:"./coverage-results/report"

echo 'Report can be found at: ./coverage-results/report'